# CLASSIFICATION_PR-HEART ATTACK PREDICTION

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import  RandomForestClassifier

In [3]:
df = pd.read_csv("C:/Users/mohan/Downloads/heart_attack_prediction_india (2).csv")
df

,Age,Gender,Chest Pain Type,Resting Blood Pressure,Cholesterol,Resting ECG Results,Smoking History,Diabetes History,Alcohol Consumption,Heart Attack Risk
0,69,0,4,109,487,1,1,0,0,0
1,32,0,2,125,170,1,0,0,0,1
2,89,0,2,186,543,0,0,0,1,0
3,78,0,2,104,367,0,1,0,1,1
4,38,1,1,151,158,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...
6995,69,1,4,144,110,0,0,0,1,0
6996,23,0,1,177,481,0,0,1,1,1
6997,86,1,2,174,315,0,0,1,0,1
6998,91,0,4,198,129,1,1,0,1,0
6999,26,0,3,132,193,0,1,1,0,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7000 entries, 0 to 6999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     7000 non-null   int64
 1   Gender                  7000 non-null   int64
 2   Chest Pain Type         7000 non-null   int64
 3   Resting Blood Pressure  7000 non-null   int64
 4   Cholesterol             7000 non-null   int64
 5   Resting ECG Results     7000 non-null   int64
 6   Smoking History         7000 non-null   int64
 7   Diabetes History        7000 non-null   int64
 8   Alcohol Consumption     7000 non-null   int64
 9   Heart Attack Risk       7000 non-null   int64
dtypes: int64(10)
memory usage: 547.0 KB

In [5]:
df.describe()

,Age,Gender,Chest Pain Type,Resting Blood Pressure,Cholesterol,Resting ECG Results,Smoking History,Diabetes History,Alcohol Consumption,Heart Attack Risk
count,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000
mean,58.227857,0.492571,2.507857,144.207857,351.351000,0.489571,0.497714,0.493571,0.489000,0.500429
std,23.511403,0.499981,1.119491,31.682105,146.303141,0.499927,0.500030,0.499994,0.499915,0.500036
min,18.000000,0.000000,1.000000,90.000000,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,38.000000,0.000000,2.000000,117.000000,223.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,58.000000,0.000000,3.000000,144.000000,354.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,78.000000,1.000000,4.000000,172.000000,480.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,99.000000,1.000000,4.000000,199.000000,599.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [6]:
df2=df.copy()
df2

,Age,Gender,Chest Pain Type,Resting Blood Pressure,Cholesterol,Resting ECG Results,Smoking History,Diabetes History,Alcohol Consumption,Heart Attack Risk
0,69,0,4,109,487,1,1,0,0,0
1,32,0,2,125,170,1,0,0,0,1
2,89,0,2,186,543,0,0,0,1,0
3,78,0,2,104,367,0,1,0,1,1
4,38,1,1,151,158,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...
6995,69,1,4,144,110,0,0,0,1,0
6996,23,0,1,177,481,0,0,1,1,1
6997,86,1,2,174,315,0,0,1,0,1
6998,91,0,4,198,129,1,1,0,1,0
6999,26,0,3,132,193,0,1,1,0,1

In [7]:
df.isnull().sum()

Age                       0
Gender                    0
Chest Pain Type           0
Resting Blood Pressure    0
Cholesterol               0
Resting ECG Results       0
Smoking History           0
Diabetes History          0
Alcohol Consumption       0
Heart Attack Risk         0
dtype: int64

In [8]:
df.shape

(7000, 10)

In [9]:
df.corr()

,Age,Gender,Chest Pain Type,Resting Blood Pressure,Cholesterol,Resting ECG Results,Smoking History,Diabetes History,Alcohol Consumption,Heart Attack Risk
Age,1.000000,0.006276,-0.000418,0.014267,-0.011023,-0.015448,-0.024171,0.004056,0.008874,0.009113
Gender,0.006276,1.000000,0.011208,0.001356,-0.001790,0.009122,0.004504,-0.003335,-0.016047,0.030588
Chest Pain Type,-0.000418,0.011208,1.000000,0.007630,0.016219,0.006273,0.009348,0.011577,0.000665,0.004078
Resting Blood Pressure,0.014267,0.001356,0.007630,1.000000,-0.025048,0.001973,-0.002824,0.002750,0.003568,-0.008443
Cholesterol,-0.011023,-0.001790,0.016219,-0.025048,1.000000,0.008185,-0.002427,-0.008566,0.009728,-0.011376
Resting ECG Results,-0.015448,0.009122,0.006273,0.001973,0.008185,1.000000,0.013336,-0.009985,0.006973,-0.045706
Smoking History,-0.024171,0.004504,0.009348,-0.002824,-0.002427,0.013336,1.000000,0.024801,-0.005531,0.011718
Diabetes History,0.004056,-0.003335,0.011577,0.002750,-0.008566,-0.009985,0.024801,1.000000,-0.007714,0.005726
Alcohol Consumption,0.008874,-0.016047,0.000665,0.003568,0.009728,0.006973,-0.005531,-0.007714,1.000000,0.000019
Heart Attack Risk,0.009113,0.030588,0.004078,-0.008443,-0.011376,-0.045706,0.011718,0.005726,0.000019,1.000000

In [10]:
df

,Age,Gender,Chest Pain Type,Resting Blood Pressure,Cholesterol,Resting ECG Results,Smoking History,Diabetes History,Alcohol Consumption,Heart Attack Risk
0,69,0,4,109,487,1,1,0,0,0
1,32,0,2,125,170,1,0,0,0,1
2,89,0,2,186,543,0,0,0,1,0
3,78,0,2,104,367,0,1,0,1,1
4,38,1,1,151,158,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...
6995,69,1,4,144,110,0,0,0,1,0
6996,23,0,1,177,481,0,0,1,1,1
6997,86,1,2,174,315,0,0,1,0,1
6998,91,0,4,198,129,1,1,0,1,0
6999,26,0,3,132,193,0,1,1,0,1

In [11]:
y=df["Heart Attack Risk"]
y

0       0
1       1
2       0
3       1
4       1
       ..
6995    0
6996    1
6997    1
6998    0
6999    1
Name: Heart Attack Risk, Length: 7000, dtype: int64

In [12]:
x=df.drop(columns="Heart Attack Risk",axis=1)
x

,Age,Gender,Chest Pain Type,Resting Blood Pressure,Cholesterol,Resting ECG Results,Smoking History,Diabetes History,Alcohol Consumption
0,69,0,4,109,487,1,1,0,0
1,32,0,2,125,170,1,0,0,0
2,89,0,2,186,543,0,0,0,1
3,78,0,2,104,367,0,1,0,1
4,38,1,1,151,158,0,0,0,1
...,...,...,...,...,...,...,...,...,...
6995,69,1,4,144,110,0,0,0,1
6996,23,0,1,177,481,0,0,1,1
6997,86,1,2,174,315,0,0,1,0
6998,91,0,4,198,129,1,1,0,1
6999,26,0,3,132,193,0,1,1,0

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
obj_1=StandardScaler()
x_train_scaled=obj_1.fit_transform(x_train)
x_test_scaled=obj_1.transform(x_test)

In [14]:
df['Heart Attack Risk'].value_counts()

Heart Attack Risk
1    3503
0    3497
Name: count, dtype: int64

In [15]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(sampling_strategy='minority')
X_sm, y_sm = smote.fit_resample(x_train, y_train)

y_sm.value_counts()

Heart Attack Risk
0    2820
1    2820
Name: count, dtype: int64

# LOGISTIC REGRESSION

In [16]:
model1=LogisticRegression()
model1.fit(x_train,y_train)

LogisticRegression()

In [17]:
#testing accuracy
y_pred=model1.predict(x_test)
fs=accuracy_score(y_pred,y_test)
fs

0.5121428571428571

In [18]:
#training accuracy
y_train_pred=model1.predict(x_train)
final_training=accuracy_score(y_train_pred,y_train)
final_training

0.51875

In [19]:
from sklearn.metrics import confusion_matrix, classification_report

cr = classification_report(y_test, y_pred, target_names=["0", "1"])

print("\nClassification Report:")
print(cr)

Classification Report:
              precision    recall  f1-score   support

           0       0.53      0.47      0.50       717
           1       0.50      0.56      0.53       683

    accuracy                           0.51      1400
   macro avg       0.51      0.51      0.51      1400
weighted avg       0.51      0.51      0.51      1400

# KNN

In [20]:
model2=KNeighborsClassifier()
model2.fit(x_train,y_train)

KNeighborsClassifier()

In [21]:
#testing accuracy
y_pred=model2.predict(x_test)
fs=accuracy_score(y_pred,y_test)
fs

0.4857142857142857

In [22]:
#training accuracy
y_train_pred=model2.predict(x_train)
final_training=accuracy_score(y_train_pred,y_train)
final_training

0.6766071428571429

In [23]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint


param_dist ={'n_neighbors': [3,5,7], 'metric': ['euclidean', 'manhattan'] }

rf =KNeighborsClassifier()

rand_search = RandomizedSearchCV(rf, param_distributions = param_dist,n_iter=5, cv=5,verbose=1, n_jobs=-1)

rand_search.fit(x_train, y_train)
print("Best Hyperparameters:")
print(rand_search.best_params_)

Fitting 5 folds for each of 5 candidates, totalling 25 fits
Best Hyperparameters:
{'n_neighbors': 3, 'metric': 'manhattan'}

In [24]:
model23=KNeighborsClassifier(n_neighbors=3, metric='manhattan')
model23.fit(x_train,y_train)

KNeighborsClassifier(metric='manhattan', n_neighbors=3)

In [25]:
#testing accuracy
y_pred=model23.predict(x_test)
fs=accuracy_score(y_pred,y_test)
fs

0.5135714285714286

In [26]:
#training accuracy
y_train_pred=model2.predict(x_train)
final_training=accuracy_score(y_train_pred,y_train)
final_training

0.6766071428571429

In [27]:
from sklearn.metrics import confusion_matrix, classification_report

cr = classification_report(y_test, y_pred, target_names=["0", "1"])

print("\nClassification Report:")
print(cr)

Classification Report:
              precision    recall  f1-score   support

           0       0.53      0.51      0.52       717
           1       0.50      0.51      0.51       683

    accuracy                           0.51      1400
   macro avg       0.51      0.51      0.51      1400
weighted avg       0.51      0.51      0.51      1400

# SVM

In [28]:
model3=SVC()
model3.fit(x_train,y_train)

SVC()

In [29]:
#testing accuracy
y_pred=model3.predict(x_test)
fs=accuracy_score(y_pred,y_test)
fs

0.48857142857142855

In [30]:
#training accuracy
y_train_pred=model3.predict(x_train)
final_training=accuracy_score(y_train_pred,y_train)
final_training

0.5160714285714286

In [31]:
from sklearn.model_selection import GridSearchCV 
model_1 = SVC()
parameter = {'C': [0.1, 1, 7,0.4], 'kernel': ['linear', 'rbf'] }
grid = GridSearchCV( estimator=model_1, param_grid=parameter, cv=5, scoring='accuracy' )
grid.fit(x_train, y_train)
print("Best parameters:", grid.best_params_)
print("Best CV score:", grid.best_score_)

Best parameters: {'C': 0.1, 'kernel': 'linear'}
Best CV score: 0.5232142857142856

In [32]:
model34=SVC(C=0.1, kernel='linear')
model34.fit(x_train,y_train)

SVC(C=0.1, kernel='linear')

In [33]:
#testing accuracy
y_pred=model34.predict(x_test)
fs=accuracy_score(y_pred,y_test)
fs

0.5214285714285715

In [34]:
#training accuracy
y_train_pred=model34.predict(x_train)
final_training=accuracy_score(y_train_pred,y_train)
final_training

0.5232142857142857

In [35]:
from sklearn.metrics import confusion_matrix, classification_report

cr = classification_report(y_test, y_pred, target_names=["0", "1"])

print("\nClassification Report:")
print(cr)

Classification Report:
              precision    recall  f1-score   support

           0       0.53      0.52      0.53       717
           1       0.51      0.52      0.52       683

    accuracy                           0.52      1400
   macro avg       0.52      0.52      0.52      1400
weighted avg       0.52      0.52      0.52      1400

# NAIVE BAYES

In [36]:
model4=GaussianNB()
model4.fit(x_train,y_train)

GaussianNB()

In [37]:
#testing accuracy
y_pred=model4.predict(x_test)
fs=accuracy_score(y_pred,y_test)
fs

0.5071428571428571

In [38]:
#training accuracy
y_train_pred=model4.predict(x_train)
final_training=accuracy_score(y_train_pred,y_train)
final_training

0.5273214285714286

In [39]:
from sklearn.metrics import confusion_matrix, classification_report

cr = classification_report(y_test, y_pred, target_names=["0", "1"])

print("\nClassification Report:")
print(cr)

Classification Report:
              precision    recall  f1-score   support

           0       0.52      0.47      0.49       717
           1       0.50      0.55      0.52       683

    accuracy                           0.51      1400
   macro avg       0.51      0.51      0.51      1400
weighted avg       0.51      0.51      0.51      1400

# DECISION TREE

In [40]:
df2

,Age,Gender,Chest Pain Type,Resting Blood Pressure,Cholesterol,Resting ECG Results,Smoking History,Diabetes History,Alcohol Consumption,Heart Attack Risk
0,69,0,4,109,487,1,1,0,0,0
1,32,0,2,125,170,1,0,0,0,1
2,89,0,2,186,543,0,0,0,1,0
3,78,0,2,104,367,0,1,0,1,1
4,38,1,1,151,158,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...
6995,69,1,4,144,110,0,0,0,1,0
6996,23,0,1,177,481,0,0,1,1,1
6997,86,1,2,174,315,0,0,1,0,1
6998,91,0,4,198,129,1,1,0,1,0
6999,26,0,3,132,193,0,1,1,0,1

In [41]:
y=df2["Heart Attack Risk"]
y

0       0
1       1
2       0
3       1
4       1
       ..
6995    0
6996    1
6997    1
6998    0
6999    1
Name: Heart Attack Risk, Length: 7000, dtype: int64

In [42]:
x=df2.drop(columns="Heart Attack Risk",axis=1)
x

,Age,Gender,Chest Pain Type,Resting Blood Pressure,Cholesterol,Resting ECG Results,Smoking History,Diabetes History,Alcohol Consumption
0,69,0,4,109,487,1,1,0,0
1,32,0,2,125,170,1,0,0,0
2,89,0,2,186,543,0,0,0,1
3,78,0,2,104,367,0,1,0,1
4,38,1,1,151,158,0,0,0,1
...,...,...,...,...,...,...,...,...,...
6995,69,1,4,144,110,0,0,0,1
6996,23,0,1,177,481,0,0,1,1
6997,86,1,2,174,315,0,0,1,0
6998,91,0,4,198,129,1,1,0,1
6999,26,0,3,132,193,0,1,1,0

In [43]:
x2_train,x2_test,y2_train,y2_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [44]:
model5= DecisionTreeClassifier()
model5.fit(x2_train,y2_train)

DecisionTreeClassifier()

In [45]:
#testing accuracy
y2_pred=model5.predict(x2_test)
fs=accuracy_score(y2_pred,y2_test)
fs

0.5035714285714286

In [46]:
#training accuracy
y2_train_pred=model5.predict(x2_train)
final_training=accuracy_score(y2_train_pred,y2_train)
final_training

1.0

In [47]:
param_grid = {
    'max_depth': [3, 5, 10],
    'min_samples_split': [2,5,6,7,3,10],
    'min_samples_leaf': [1, 2,3,4]
}
grid_search = GridSearchCV(
    estimator=model5,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)
grid_search.fit(x2_train, y2_train)
print("Best Parameters:", grid_search.best_params_)
best_model = grid_search.best_estimator_
y2_pred = best_model.predict(x2_test)
print("Accuracy:", accuracy_score(y2_test,y2_pred))

Best Parameters: {'max_depth': 5, 'min_samples_leaf': 4, 'min_samples_split': 7}
Accuracy: 0.5135714285714286

In [48]:
model56= DecisionTreeClassifier(max_depth=5, min_samples_leaf=4, min_samples_split=7)
model56.fit(x2_train,y2_train)

DecisionTreeClassifier(max_depth=5, min_samples_leaf=4, min_samples_split=7)

In [49]:
#testing accuracy
y2_pred=model56.predict(x2_test)
fs=accuracy_score(y2_pred,y2_test)
fs

0.5135714285714286

In [50]:
#training accuracy
y2_train_pred=model56.predict(x2_train)
final_training=accuracy_score(y2_train_pred,y2_train)
final_training

0.5585714285714286

In [51]:
from sklearn.metrics import confusion_matrix, classification_report

cr = classification_report(y_test, y_pred, target_names=["0", "1"])

print("\nClassification Report:")
print(cr)

Classification Report:
              precision    recall  f1-score   support

           0       0.52      0.47      0.49       717
           1       0.50      0.55      0.52       683

    accuracy                           0.51      1400
   macro avg       0.51      0.51      0.51      1400
weighted avg       0.51      0.51      0.51      1400

# RANDOM FOREST

In [52]:
model6=RandomForestClassifier()
model6.fit(x2_train, y2_train)

RandomForestClassifier()

In [53]:
#testing accuracy
y2_pred=model6.predict(x2_test)
fs=accuracy_score(y2_pred,y2_test)
fs

0.5092857142857142

In [54]:
#training accuracy
y2_train_pred=model6.predict(x2_train)
final_training=accuracy_score(y2_train_pred,y2_train)
final_training

1.0

In [55]:
accuracy =model6.score(x_test, y_test)
print("Model Accuracy:", accuracy)

Model Accuracy: 0.5092857142857142

In [56]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint


param_dist = {'n_estimators': randint(50,500),
              'max_depth': randint(1,20)}

rf = RandomForestClassifier()

rand_search = RandomizedSearchCV(rf, param_distributions = param_dist,n_iter=5, cv=5,verbose=1, n_jobs=-1)

rand_search.fit(x2_train, y2_train)
print("Best Hyperparameters:")
print(rand_search.best_params_)

Fitting 5 folds for each of 5 candidates, totalling 25 fits
Best Hyperparameters:
{'max_depth': 1, 'n_estimators': 407}

In [58]:
model67=RandomForestClassifier(max_depth=1, n_estimators=407)
model67.fit(x2_train, y2_train)

RandomForestClassifier(max_depth=1, n_estimators=407)

In [59]:
#testing accuracy
y2_pred=model67.predict(x2_test)
fs=accuracy_score(y2_pred,y2_test)
fs

0.5092857142857142

In [60]:
# training accurac
y2_train_pred=model67.predict(x2_train)
final_training=accuracy_score(y2_train_pred,y2_train)
final_training

0.5264285714285715

In [61]:
from sklearn.metrics import confusion_matrix, classification_report

cr = classification_report(y_test, y_pred, target_names=["0", "1"])

print("\nClassification Report:")
print(cr)

Classification Report:
              precision    recall  f1-score   support

           0       0.52      0.47      0.49       717
           1       0.50      0.55      0.52       683

    accuracy                           0.51      1400
   macro avg       0.51      0.51      0.51      1400
weighted avg       0.51      0.51      0.51      1400

In [62]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

xgb = XGBClassifier()

xgb.fit(x2_train, y2_train)
y2_pred = xgb.predict(x2_test)

print("XGBoost Test Accuracy:", accuracy_score(y2_test, y2_pred))

XGBoost Test Accuracy: 0.5071428571428571

In [63]:
# training accurac
y2_train_pred=xgb.predict(x2_train)
final_training=accuracy_score(y2_train_pred,y2_train)
final_training

0.9316071428571429